name: Build & Deploy for SmartQuiz


on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build-deploy:
        name: Build & Deploy for SmartQuiz
        runs-on: ubuntu-latest

        steps:
            - name: Cache dependencies
              uses: actions/cache@v3 
              with:
                 path: ~/.npm
                 key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v3 
                 restore-keys: |
                     ${{ runner.os }}-node-v3

            - name: Checking out the Code
              uses: actions/checkout@v3
                              
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '21.6.1'

            - name: Run Dependencies
              run: npm install
            
        

            - name: Build Application
              run: npm run build
